version: "3"
services:

  # PHP-FPM
  #=============================================================================
  app:
    volumes:
      - lara-forum-sync:/var/www/${COMPOSE_PROJECT_NAME}:nocopy

  # NGINX Server
  #=============================================================================
  webserver:
    ports:
      - "8000:80"
    volumes:
      - lara-forum-sync:/var/www/${COMPOSE_PROJECT_NAME}:nocopy

# DOCKER VOLUMES
#===============================================================================
volumes:
  lara-forum-sync:
    external: true
