version: "3"
services:

  # PHP-FPM
  #=============================================================================
  app:
    build:
      context: ./docker
      dockerfile: app/Dockerfile
      args:
        - APP_PHP_VERSION=${PHP_VERSION}
        - APP_NAME=${COMPOSE_PROJECT_NAME}
        - APP_NODE_JS_VERSION=${NODE_JS_VERSION}
    networks:
      - app-network
    volumes:
      - ./src:/var/www/${COMPOSE_PROJECT_NAME}
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  # NGINX Server
  #=============================================================================
  webserver:
    build:
      context: ./docker
      dockerfile: nginx/Dockerfile
      args:
        - APP_NAME=${COMPOSE_PROJECT_NAME}
    links:
      - app
    depends_on:
      - app
    networks:
      - app-network
    volumes:
      - ./src:/var/www/${COMPOSE_PROJECT_NAME}
      - ./docker/nginx/app.conf:/home/root/nginx/app.conf

  # DATABASE
  #=============================================================================
  db:
    image: mysql:5.7.22
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: lara-forum
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: lara-forum
    volumes:
      - db-data:/var/lib/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - app-network

# DOCKER NETWORKS
#===============================================================================
networks:
  app-network:
    driver: bridge

# DOCKER VOLUMES
#===============================================================================
volumes:
  db-data:
    driver: local
