version: "3"
services:

  # PHP-FPM
  #=============================================================================
  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile
    networks:
      - laravel-template-network
    volumes:
      - laravel-template-sync:/var/www:nocopy
      - ./.docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini

  # NGINX Server
  #=============================================================================
  webserver:
    image: nginx:alpine
    ports:
      - "8000:80"
    links:
      - app
    depends_on:
      - app
    networks:
      - laravel-template-network
    volumes:
      - laravel-template-sync:/var/www:nocopy
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/

  # DATABASE
  #=============================================================================
  db:
    image: mysql:5.7.22
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_DATABASE: laravel
    volumes:
      - db-data:/var/lib/mysql
      - ./.docker/mysql/my.cnf:/etc/mysql/my.cnf
    networks:
      - laravel-template-network

# DOCKER NETWORKS
#===============================================================================
networks:
  laravel-template-network:
    driver: bridge

# DOCKER VOLUMES
#===============================================================================
volumes:
  laravel-template-sync:
    external: true
  db-data:
    driver: local
